version: "3.8"
services:
  frontend:
    build: ./my-project
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DB_CONNECTION=mongodb://mongo:27017/expenseDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
